@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@module = department

## 查询所有

GET  http://{{host}}/{{module}}/ HTTP/1.1
content-type: {{contentType}}

### 查询ID

GET  http://{{host}}/{{module}}/1 HTTP/1.1
content-type: {{contentType}}

### 错误查询ID

GET  http://{{host}}/{{module}}/abc HTTP/1.1
content-type: {{contentType}}


### 新增

POST http://{{host}}/{{module}}/ HTTP/1.1
content-type: {{contentType}}

{
    "name": "憨批总公司",
    "parentId": 0,
    "level": "1",
    "seq": 2,
    "remark": "",
    "operator": "无",
    "operatorTime": "2020-04-15T21:18:21.000Z",
    "operatorIp": ""
}

### 修改

PUT http://{{host}}/{{module}}/2 HTTP/1.1
content-type: {{contentType}}

{
    "name": "xxx总公司",
    "parentId": 0,
    "level": "1",
    "seq": 1,
    "remark": "",
    "operator": "无",
    "operatorTime": "2020-04-15T21:18:21.000Z",
    "operatorIp": ""
}


### 删除

DELETE http://{{host}}/{{module}}/1 HTTP/1.1
content-type: {{contentType}}