@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@module = processCata

## 查询所有

GET  http://{{host}}/{{module}}/ HTTP/1.1
content-type: {{contentType}}

### 查询ID

GET  http://{{host}}/{{module}}/1 HTTP/1.1
content-type: {{contentType}}

### 错误查询ID

GET  http://{{host}}/{{module}}/abc HTTP/1.1
content-type: {{contentType}}


### 新增

POST http://{{host}}/{{module}}/ HTTP/1.1
content-type: {{contentType}}

{
    "cataCode": "FLBM10-0001-01",
    "cataName": "袖口整理",
    "cataStatus": 0,
    "cataRemark": "袖口整理"
}

### 修改

PUT http://{{host}}/{{module}}/2 HTTP/1.1
content-type: {{contentType}}

{
    "cataCode": "FLBM10-0001-01",
    "cataName": "袖口整理",
    "cataStatus": 0,
    "cataRemark": "袖口整理"
}


### 删除

DELETE http://{{host}}/{{module}}/1 HTTP/1.1
content-type: {{contentType}}