@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@module = users

## 查询所有

GET  http://{{host}}/{{module}}/ HTTP/1.1
content-type: {{contentType}}

### 查询ID

GET  http://{{host}}/{{module}}/1 HTTP/1.1
content-type: {{contentType}}

### 错误查询ID

GET  http://{{host}}/{{module}}/abc HTTP/1.1
content-type: {{contentType}}


### 新增

POST http://{{host}}/{{module}}/ HTTP/1.1
content-type: {{contentType}}

{
    "username": "sample",
    "telephone": "15229371873",
    "mail": "jiangfei.ng@foxmail.com",
    "sex": 1,
    "education": "本科",
    "job": "程序员",
    "password": "123",
    "remark": "学识渊博",
    "status": 1,
    "depId": 1
}

### 修改

PUT http://{{host}}/{{module}}/2 HTTP/1.1
content-type: {{contentType}}

{
    "username": "jiangfei2",
    "telephone": "15229371873",
    "mail": "jiangfei.ng@foxmail.com",
    "sex": 1,
    "education": "本科",
    "job": "程序员",
    "password": "333",
    "remark": "学识ok",
    "status": 1,
    "depId": 1
}


### 删除

DELETE http://{{host}}/{{module}}/1 HTTP/1.1
content-type: {{contentType}}